rem ========== BASE ENV ==========
SET INTERNAL=%~dp0
SET INTERNAL=%INTERNAL:~0,-1%
rem overriding windows user/local environment
SET LOCALENV_DIR=%INTERNAL%\_e
SET TMP=%LOCALENV_DIR%\t
SET TEMP=%LOCALENV_DIR%\t
SET HOME=%LOCALENV_DIR%\u
SET HOMEPATH=%LOCALENV_DIR%\u
SET USERPROFILE=%LOCALENV_DIR%\u
SET LOCALAPPDATA=%USERPROFILE%\AppData\Local
SET APPDATA=%USERPROFILE%\AppData\Roaming

rem ========== PYTHON ENV ==========
SET PYTHON_PATH=%INTERNAL%\python_env
rem overriding default python env vars in order not to interfere with any system python installation
SET PYTHONHOME=
SET PYTHONPATH=
SET PYTHONEXECUTABLE=%PYTHON_PATH%\python.exe
SET PYTHONWEXECUTABLE=%PYTHON_PATH%pythonw.exe
SET PYTHON_EXECUTABLE=%PYTHON_PATH%\python.exe
SET PYTHONW_EXECUTABLE=%PYTHON_PATH%pythonw.exe
SET PYTHON_BIN_PATH=%PYTHON_EXECUTABLE%
SET PYTHON_LIB_PATH=%PYTHON_PATH%\Lib\site-packages
SET PATH=%PYTHON_PATH%;%PYTHON_PATH%\Scripts;%PATH%



rem ========== MSVC ENV ==========
SET MVS=%INTERNAL%\Microsoft Visual Studio
SET MSVC=%MVS%\2019\Community\VC\Tools\MSVC\14.29.30133
SET KITS=%INTERNAL%\windows_kits\10\10.0.19041.0
SET LIB=%MSVC%\lib\x64
rem SET LIB=%MSVC%\lib\x86;%LIB%
SET LIB=%PYTHON_PATH%\libs;%LIB%
SET LIB=%KITS%\Lib\10.0.19041.0\ucrt\x86;%LIB%
SET LIB=%KITS%\Lib\10.0.19041.0\ucrt\x64;%LIB%
SET LIB=%KITS%\Lib\10.0.19041.0\um\x64;%LIB%
SET INCLUDE=%MSVC%\include
SET INCLUDE=%KITS%\Include\10.0.19041.0\ucrt;%INCLUDE%
SET PATH=%MSVC%\bin\Hostx64\x64;%PATH%
SET PATH=%INTERNAL%\ninja;%PATH%
SET GIT=%INTERNAL%\git\bin
SET PATH=%GIT%;%PATH%

rem ========== CUDA ENV ==========
SET PATH=%INTERNAL%\CUDA;%INTERNAL%\CUDNN;%PATH%
SET CUDA_PATH=%INTERNAL%\CUDA\
SET CUDA_HOME=%INTERNAL%\CUDA\
SET PATH=%CUDA_PATH%;%CUDA_HOME%;%PATH%